### ISSUE TITLE
Combine powers

### ISSUE THREAD

**Issue by fommil** [hasufell/ghcup#1]
Should we combine our projects and try to get this accepted upstream? e.g. maybe as a new way of distributing the Haskell Platform...

https://gitlab.com/fommil/ghc-env

I'm very happy to delete my project if the features can be moved to ghcup.

Similar projects: https://gitlab.com/fommil/ghc-env/issues/5

**Comment by hasufell** [comment]
The biggest problem currently is to have a reliable method to get the right tarball, see https://github.com/hasufell/ghcup/blob/master/ghcup.sh#L224

If this can be straightened out, then there could be a chance of upstreaming it. Otherwise I think people will constantly complain "doesn't download on my distro".

Wrt the other projects, I haven't had a look yet, but combining could be useful. Currently I will be using this at work (and possibly some of my colleagues). Do you have a list of features you would add to this?

**Comment by hasufell** [comment]
Installing from source in it's own is easy. What will not be easy is to make sure the system toolchain is properly set up, dependencies exist (gcc, llvm, ...). In most cases the ghc configure script will fail with a very specific error. In that case we would have to give some useful distro-specific help-instruction in case the configure script fails. It could be possible.

Cabal-install support should also be relatively easy. Maybe a `install-cabal` and `set-cabal` subcommand.

**Comment by fommil** [comment]
no need for `set-cabal` since there is only supposed to be only one `cabal` in the system. The user's `~/.cabal/bin` should live ahead of the `~/.ghcup/bin` so that a `cabal new-install cabal` gives priority to the one the user requests.

I'm perfectly fine for `./configure` errors to be seen verbatim, no need to sugar coat it. Might be worth a quick sanity check beforehand for things we know are necessary: `gcc`, `alex`, `happy`.

**Comment by fommil** [comment]
btw, my script is GPLv3 but feel free to take what you want under whatever license you want.

**Comment by hasufell** [comment]
> no need for `set-cabal` since there is supposed to be only one `cabal` in the system. The user's `~/.cabal/bin` should live ahead of the `~/.ghcup/bin` so that a `cabal new-install cabal` gives priority to the one the user requests.

I think the simplest solution here is to install into `~/.cabal/bin` with a safety check instead of managing two versions and then have the user tell how to fix his `PATH`: https://github.com/hasufell/ghcup/commit/ea2d5c20d9a401324897b584e53ec4f3be105369

**Comment by hasufell** [comment]
Is there anything else outstanding?

**Comment by hvr** [comment]
@hasufell one thing that might be useful specifically w/ the compilation mode: allow non-standard configurations of GHC to be built; e.g. w/ `integer-simple` instead of `integer-gmp`

**Comment by hasufell** [comment]
@hvr yes, I thought about that and I think the simplest solution is to just allow the user to specify a custom `mk/build.mk` to be used for the build.

**Comment by hasufell** [comment]
> I think the simplest solution here is to install into `~/.cabal/bin` with a safety check instead of managing two versions and then have the user tell how to fix his ``

unfortunately, this doesn't seem to work very well, because `cabal new-install` will never overwrite the old binary and I don't see a way to tell it "yes, force overwrite", which makes this command unidiomatic, because you have to move cabal to a temporary place in your PATH, then install, then remove the old...

**Comment by fommil** [comment]
thank you so much! I don't think I have anything else to contribute so I will delete my `ghc-env` script and use ghcup instead :laughing: 

For posterity, this is the list of similar projects I found 

Do something combined with

- https://github.com/sol/ghc-env
- https://github.com/mitchellwrosen/ghc-switch
- https://haskell.futurice.com/
- https://launchpad.net/~hvr/+archive/ubuntu/ghc
- https://github.com/haskell/cabal#installing-cabal-without-cabal
